# permissions for end users to edit podpacketdumpers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podpacketdumper-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kn-operator-sdk
    app.kubernetes.io/part-of: kn-operator-sdk
    app.kubernetes.io/managed-by: kustomize
  name: podpacketdumper-editor-role
rules:
- apiGroups:
  - tcpdump.kyeongna.io
  resources:
  - podpacketdumpers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tcpdump.kyeongna.io
  resources:
  - podpacketdumpers/status
  verbs:
  - get
