---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tcpdump.kyeongna.io
  resources:
  - podpacketdumpers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tcpdump.kyeongna.io
  resources:
  - podpacketdumpers/finalizers
  verbs:
  - update
- apiGroups:
  - tcpdump.kyeongna.io
  resources:
  - podpacketdumpers/status
  verbs:
  - get
  - patch
  - update
